networks:
  default:
    driver: bridge
    
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - default
    volumes:
      - ./:/app
    ports:
    - "5000:5000"
    env_file:
      - .env
      
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
    - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: